#!/bin/bash
# Generate config.js from Netlify environment variables at build time
# This keeps secrets out of the git repo

cat > src/config.js << 'CONFIGEOF'
// Configuration for the Albums Collection App
// Auto-generated by build-config.sh from environment variables
window.CONFIG = {
    DISCOGS: {
        API_KEY: '${DISCOGS_API_KEY}',
        BASE_URL: 'https://api.discogs.com',
        HEADERS: { 'User-Agent': 'AlbumsCollectionApp/1.0' },
        RATE_LIMIT: {
            MAX_RETRIES: 5,
            DELAY: 2000,
            MAX_429_RETRIES: 15,
            MAX_DELAY: 300000,
            SCRAPER_DELAY: 3000,
            PAGE_DELAY: 5000
        }
    },

    GOOGLE_SHEETS: {
        API_KEY: '${GOOGLE_SHEETS_API_KEY}',
        SPREADSHEET_ID: '${GOOGLE_SHEETS_SPREADSHEET_ID}',
        SHEETS: { ALBUMS: 'Albums', SCRAPED_HISTORY: 'Scraped_History' },
        API: {
            BASE_URL: 'https://sheets.googleapis.com/v4/spreadsheets',
            RATE_LIMIT: { MAX_REQUESTS: 90, TIME_WINDOW: 100000, BATCH_SIZE: 25, DELAY_BETWEEN_BATCHES: 2000 }
        }
    },

    DATA_BACKEND: 'supabase',

    SPOTIFY: {
        CLIENT_ID: '${SPOTIFY_CLIENT_ID}',
        REDIRECT_URI: ''
    },

    FILTERS: {
        EXCLUDE_WORDS: ['compilation', 'single', 'Shellac', 'EP', '10"', '7"', 'Transcription', 'reissue', 'remastered'],
        ALBUM_KEYWORDS: ['album', 'lp'],
        EXCLUDE_SLASH_IN_TITLE: false,
        EXCLUDE_VARIOUS_ARTISTS: true
    },

    UI: {
        ITEMS_PER_PAGE: 20,
        MAX_SEARCH_RESULTS: 50,
        ANIMATION_DURATION: 300,
        LOADING_DELAY: 500
    },

    MODELS: {
        ALBUM: { REQUIRED_FIELDS: ['id', 'title', 'year', 'artist'], OPTIONAL_FIELDS: ['genres', 'styles', 'tracklist', 'credits', 'formats', 'images', 'role', 'type'] },
        ARTIST: { REQUIRED_FIELDS: ['id', 'name'], OPTIONAL_FIELDS: ['image', 'albumCount'] },
        TRACK: { REQUIRED_FIELDS: ['title'], OPTIONAL_FIELDS: ['duration', 'position', 'frequency'] },
        ROLE: { REQUIRED_FIELDS: ['name'], OPTIONAL_FIELDS: ['frequency', 'artists'] }
    },

    SUPABASE: {
        URL: '${SUPABASE_URL}',
        ANON_KEY: '${SUPABASE_ANON_KEY}',
        SERVICE_ROLE_KEY: '',
        TABLES: {
            ALBUMS: 'albums', ARTISTS: 'artists', TRACKS: 'tracks', ROLES: 'roles',
            ALBUM_ARTISTS: 'album_artists', ALBUM_TRACKS: 'album_tracks',
            ARTIST_ROLES: 'artist_roles', COLLECTIONS: 'collections',
            COLLECTION_ALBUMS: 'collection_albums', SCRAPED_ARTISTS_HISTORY: 'scraped_artists_history'
        },
        DATABASE: { BATCH_SIZE: 100, MAX_RETRY_ATTEMPTS: 3, TIMEOUT: 30000, ENABLE_REALTIME: true, ENABLE_RLS: false },
        SYNC: { AUTO_SYNC: true, SYNC_INTERVAL: 30000, OFFLINE_MODE: false, CONFLICT_RESOLUTION: 'server_wins' }
    },

    USER_MANAGEMENT: {
        URL: '${USER_MGMT_SUPABASE_URL}',
        ANON_KEY: '${USER_MGMT_SUPABASE_ANON_KEY}',
        TABLES: { USERS: 'users', USER_CREDENTIALS: 'user_credentials', USER_SESSIONS: 'user_sessions' },
        AUTH: { SESSION_TIMEOUT: 7200000, REMEMBER_ME_DURATION: 604800, PASSWORD_MIN_LENGTH: 8, REQUIRE_EMAIL_VERIFICATION: false }
    },

    DEBUG: {
        ENABLED: false,
        LOG_API_CALLS: false,
        LOG_PERFORMANCE: false,
        LOG_SUPABASE: false,
        AUTO_TEST_API: false
    }
};

window.CONFIG = CONFIG;
console.log('🔧 CONFIG: Configuration loaded successfully', {
    hasUserManagement: !!(CONFIG?.USER_MANAGEMENT),
    hasUrl: !!(CONFIG?.USER_MANAGEMENT?.URL),
    hasAnonKey: !!(CONFIG?.USER_MANAGEMENT?.ANON_KEY),
    anonKeyLength: CONFIG?.USER_MANAGEMENT?.ANON_KEY?.length || 0,
    timestamp: new Date().toISOString()
});
CONFIGEOF

# Replace placeholders with actual env vars
sed -i.bak "s|\${DISCOGS_API_KEY}|${DISCOGS_API_KEY}|g" src/config.js
sed -i.bak "s|\${GOOGLE_SHEETS_API_KEY}|${GOOGLE_SHEETS_API_KEY}|g" src/config.js
sed -i.bak "s|\${GOOGLE_SHEETS_SPREADSHEET_ID}|${GOOGLE_SHEETS_SPREADSHEET_ID}|g" src/config.js
sed -i.bak "s|\${SPOTIFY_CLIENT_ID}|${SPOTIFY_CLIENT_ID}|g" src/config.js
sed -i.bak "s|\${SUPABASE_URL}|${SUPABASE_URL}|g" src/config.js
sed -i.bak "s|\${SUPABASE_ANON_KEY}|${SUPABASE_ANON_KEY}|g" src/config.js
sed -i.bak "s|\${USER_MGMT_SUPABASE_URL}|${USER_MGMT_SUPABASE_URL}|g" src/config.js
sed -i.bak "s|\${USER_MGMT_SUPABASE_ANON_KEY}|${USER_MGMT_SUPABASE_ANON_KEY}|g" src/config.js
rm -f src/config.js.bak

echo "✅ config.js generated from environment variables"
