# Netlify Configuration for Albums Collection App
# Last Updated: July 6, 2025 - Troubleshooting MIME Type Issue

# Temporarily disable SPA redirect to fix MIME type serving
# Will re-enable with correct pattern once authentication works

# Add explicit MIME type headers for JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/src/*.js"  
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"