# Netlify Configuration for Albums Collection App
# Phase 2: Authentication-Required Setup

# Authentication-first routing
# 1. Allow direct access to auth.html (login page)
# 2. Redirect everything else to index.html (which requires authentication)

# Allow auth.html to load directly
[[redirects]]
  from = "/auth.html"
  to = "/auth.html"
  status = 200
  force = false

# Allow auth.html with query parameters
[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200
  force = false

# SPA routing for main app (requires authentication via index.html guard)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add explicit MIME type headers for remaining JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/src/*.js"  
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"