# Netlify Configuration for Albums Collection App
# Last Updated: July 6, 2025 - Config Inline Fix

# SPA (Single Page Application) routing
# Now safe to use since config is inline (no external JS MIME type issues)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add explicit MIME type headers for remaining JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/src/*.js"  
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"